.PHONY: clean All

All:
	@echo "----------Building project:[ Lab00_ex3 - Debug ]----------"
	@cd "Lab00_ex3" && "$(MAKE)" -f  "Lab00_ex3.mk"
clean:
	@echo "----------Cleaning project:[ Lab00_ex3 - Debug ]----------"
	@cd "Lab00_ex3" && "$(MAKE)" -f  "Lab00_ex3.mk" clean
