.PHONY: clean All

All:
	@echo "----------Building project:[ voti_esami - Debug ]----------"
	@cd "voti_esami" && "$(MAKE)" -f  "voti_esami.mk"
clean:
	@echo "----------Cleaning project:[ voti_esami - Debug ]----------"
	@cd "voti_esami" && "$(MAKE)" -f  "voti_esami.mk" clean
