.PHONY: clean All

All:
	@echo "----------Building project:[ Lab4_ex2 - Debug ]----------"
	@cd "C:\Users\rfran\Desktop\POLI 2 ANNO\APA\PROGRAMMAZIONE\LAB codelite\L04\Lab4_ex2" && "$(MAKE)" -f  "Lab4_ex2.mk"
clean:
	@echo "----------Cleaning project:[ Lab4_ex2 - Debug ]----------"
	@cd "C:\Users\rfran\Desktop\POLI 2 ANNO\APA\PROGRAMMAZIONE\LAB codelite\L04\Lab4_ex2" && "$(MAKE)" -f  "Lab4_ex2.mk" clean
